package com.bapseguen.dto;

public class SalePostDTO {
//	CREATE TABLE TBL_SALE_POST (
//			SALE_POST_NUMBER  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
//			MEMBER_NUMBER     NUMBER,              -- 판매자
//			TITLE             VARCHAR2(200) NOT NULL,
//			CONTENT           CLOB NOT NULL,
//			PRICE             NUMBER NOT NULL,
//			QUANTITY          NUMBER NOT NULL,
//			CATEGORY          VARCHAR2(20),
//			CREATED_DATE      DATE DEFAULT SYSDATE,
//			UPDATED_DATE      DATE,
//			DELETE_STATE      CHAR(1) DEFAULT 'N' NOT NULL,
//			IMAGE_NUMBER      NUMBER,
//			CONSTRAINT PK_TBL_SALE_POST PRIMARY KEY (SALE_POST_NUMBER),
//			CONSTRAINT FK_TBL_SALE_POST_SELLER
//			FOREIGN KEY (MEMBER_NUMBER) REFERENCES TBL_SELLER_MEMBER(MEMBER_NUMBER)
//			ON DELETE CASCADE,   -- 판매자 하드삭제 시 판매글 정리
//			CONSTRAINT FK_TBL_SALE_POST_IMAGE
//			FOREIGN KEY (IMAGE_NUMBER) REFERENCES TBL_IMAGE(IMAGE_NUMBER)
//			ON DELETE SET NULL,
//			CONSTRAINT CK_TBL_SALE_POST_CAT CHECK (CATEGORY IN ('FOOD','INGREDIENT')),
//			CONSTRAINT CK_TBL_SALE_POST_DEL CHECK (DELETE_STATE IN ('Y','N'))
//			);
	private int salePostNumber;
	private int memberNumber;
	private String title;
	private String content;
	private int price;
	private int quantitiy;
	private String category;
	private String createdDate;
	private String updatedDate;
	private String deleteDate;
	private int imgNumber;
	public int getSalePostNumber() {
		return salePostNumber;
	}
	public void setSalePostNumber(int salePostNumber) {
		this.salePostNumber = salePostNumber;
	}
	public int getMemberNumber() {
		return memberNumber;
	}
	public void setMemberNumber(int memberNumber) {
		this.memberNumber = memberNumber;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public int getPrice() {
		return price;
	}
	public void setPrice(int price) {
		this.price = price;
	}
	public int getQuantitiy() {
		return quantitiy;
	}
	public void setQuantitiy(int quantitiy) {
		this.quantitiy = quantitiy;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	public String getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(String updatedDate) {
		this.updatedDate = updatedDate;
	}
	public String getDeleteDate() {
		return deleteDate;
	}
	public void setDeleteDate(String deleteDate) {
		this.deleteDate = deleteDate;
	}
	public int getImgNumber() {
		return imgNumber;
	}
	public void setImgNumber(int imgNumber) {
		this.imgNumber = imgNumber;
	}
	@Override
	public String toString() {
		return "SalePostDTO [salePostNumber=" + salePostNumber + ", memberNumber=" + memberNumber + ", title=" + title
				+ ", content=" + content + ", price=" + price + ", quantitiy=" + quantitiy + ", category=" + category
				+ ", createdDate=" + createdDate + ", updatedDate=" + updatedDate + ", deleteDate=" + deleteDate
				+ ", imgNumber=" + imgNumber + "]";
	}

	
	
	
	
	
}
